"""Real data for the framework overview figure (Fig. 1): two genuine test-split candidates of the base fused system,
one that the two branches corroborate (AGREE keeps it) and one that only the visual branch supports (AGREE withholds it),
with the branch score curves around each and the reliability the fitted estimator assigns.
Both come from the held-out test split, scored by the seed-0 branches, and both clear the operating point tau0, so the
figure shows the reliability layer doing its job rather than a case it cannot reach.
Writes manuscript/generated/fig_framework_data.tex (pgfplots coordinates + macros).
Usage: python src/make_framework_data.py [--window 30]
"""
import os, sys, csv, math, argparse
import numpy as np
sys.path.insert(0, os.path.dirname(__file__))
from common import *
from analysis import sigmoid, load_logits
GEN = os.path.join(os.path.dirname(ROOT), "manuscript", "generated")

# The two candidates shown in Figure 1, pinned so the figure, its images and its numbers cannot drift apart.
# Both are candidates of the base fused system in one held-out test match and both clear tau0.
FIG = {
    "Keep": {"game": "spain_laliga/2016-2017/2016-11-26 - 18-15 Real Madrid 2 - 1 Gijon", "half": "1", "frame": "2121",
             "clock": "17:40", "note": "annotated Goal at 1--17:40", "img": "images/dataset-source/fig1-keep-goal.png"},
    "Drop": {"game": "spain_laliga/2016-2017/2016-11-26 - 18-15 Real Madrid 2 - 1 Gijon", "half": "2", "frame": "1258",
             "clock": "55:28", "note": "annotated Shots on target at 2--10:28, no goal", "img": "images/dataset-source/fig1-drop-shot.png"},
}

def pick(rows, tag):
    """The pinned candidate; fails loudly if a rerun no longer produces it, rather than silently showing another event."""
    w = FIG[tag]
    c = [r for r in rows if r["game"] == w["game"] and r["half"] == w["half"] and r["frame"] == w["frame"] and r["class_name"] == "Goal"]
    if not c: raise SystemExit(f"pinned Figure 1 candidate for {tag} is no longer a candidate: {w}")
    return c[0]

def curves(row, omega, W):
    g, h, f0, c = row["game"], int(row["half"]), int(row["frame"]), int(row["cls"])
    Pv = sigmoid(load_logits("visual_s0", g, h)); Pa = sigmoid(load_logits("audio_s0", g, h))
    Pf = omega * Pv + (1 - omega) * Pa
    lo, hi = max(0, f0 - W), min(Pv.shape[0], f0 + W + 1)
    t = (np.arange(lo, hi) - f0) / FPS
    co = lambda P: " ".join(f"({tt:.1f},{100*P[i, c]:.1f})" for tt, i in zip(t, range(lo, hi)))
    return co(Pv), co(Pa), co(Pf)

def main(a):
    rows = list(csv.DictReader(open(os.path.join(RESULTS, "sn_agree_test.csv"))))
    import json
    summ = json.load(open(os.path.join(RESULTS, "summary.json")))
    omega = float(summ.get("omega_by_seed", {}).get("0", summ.get("omega", 0.6)))
    tau0 = float(summ.get("tau0_by_seed", {}).get("0", summ.get("tau0", 0.4)))
    W = a.window * FPS
    M = {"fwWindow": str(a.window), "fwOmega": f"{omega:g}", "fwTau": f"{tau0:g}"}
    for tag in ("Keep", "Drop"):
        r = pick(rows, tag); M[f"fw{tag}Clock"] = FIG[tag]["clock"]; M[f"fw{tag}Note"] = FIG[tag]["note"]; M[f"fw{tag}Img"] = FIG[tag]["img"]
        name = r["game"].split("/")[-1]
        # "2017-05-20 - 21-45 Napoli 4 - 1 Fiorentina" -> date "2017-05-20", teams "Napoli 4 - 1 Fiorentina"
        import re as _re
        m = _re.match(r"^(\d{4}-\d{2}-\d{2})\s*-\s*\d{2}-\d{2}\s+(.*)$", name)
        date, teams = (m.group(1), m.group(2)) if m else (name[:10], name)
        mm, ss = divmod(int(r["frame"]) / FPS, 60)
        M[f"fw{tag}Match"] = teams.replace("_", " ")
        M[f"fw{tag}Date"] = date
        M[f"fw{tag}Time"] = f"{int(mm):02d}:{int(ss):02d} (half {r['half']})"
        for k, mk in (("p_v", "Pv"), ("p_a", "Pa"), ("p_f", "Pf"), ("A_prod", "Aprod"), ("r_agree", "R")):
            M[f"fw{tag}{mk}"] = f"{float(r[k]):.2f}"
        M[f"fw{tag}Correct"] = "true event" if r["correct"] == "1" else "false positive"
        cv, ca, cf = curves(r, omega, W)
        M[f"fw{tag}CoordsV"], M[f"fw{tag}CoordsA"], M[f"fw{tag}CoordsF"] = cv, ca, cf
        print(tag, {k: v for k, v in M.items() if k.startswith(f"fw{tag}") and "Coords" not in k}, flush=True)
    os.makedirs(GEN, exist_ok=True)
    with open(os.path.join(GEN, "fig_framework_data.tex"), "w") as fh:
        fh.write("% generated by src/make_framework_data.py -- two real test-split candidates of the base system (seed-0 branches)\n")
        for k, v in M.items(): fh.write(f"\\newcommand{{\\{k}}}{{{v}}}\n")
    print("written", os.path.join(GEN, "fig_framework_data.tex"))

if __name__ == "__main__":
    p = argparse.ArgumentParser(); p.add_argument("--window", type=int, default=30); main(p.parse_args())
